version: 2.1
orbs:
  node: circleci/node@4.3.0
  slack: circleci/slack@4.4.2
jobs:
  cancel_draft_build:
    docker:
      - image: vitalinfo/circleci-cancel-draft
    steps:
      - run: cancel-draft-build
  test_all:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: |
          yarn install --immutable
          yarn run compile
          yarn run test
      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - slack/notify:
          channel: build
          event: fail
          template: basic_fail_1
workflows:
  test:
    jobs:
      - cancel_draft_build:
          filters:
            branches:
              ignore: /develop/
          context: cancel-draft
      - test_all:
          context: slack-secret
