version: 2.1
orbs:
  node: circleci/node@4.3.0
  slack: circleci/slack@4.4.2
defaults: &defaults
  docker:
    - image: cimg/node:14.17
jobs:
  cancel_draft_build:
    docker:
      - image: vitalinfo/circleci-cancel-draft
    steps:
      - run: cancel-draft-build
  test_all:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable
      - run: yarn run compile
      - run: yarn run test:augmented:utils
      - run: yarn run test:augmented:token-weighted-pool
      - run: yarn run test
      - run: yarn run test:main:augmented:migrator-zombie
      - run: yarn run test:main:augmented:migrator-aave
      - run: yarn run test:main:augmented:migrator-comp
      - run: yarn run test:augmented:stake
      - run: yarn run build:package
      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/
          paths: .
      - slack/notify:
          channel: build
          event: fail
          template: basic_fail_1
  npm-publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: git config --global user.email "$CIRCLE_USERNAME@augmented.finance"
      - run: git config --global user.name $CIRCLE_USERNAME
      - run: npm version 1.0.0-$CIRCLE_SHA1
      - run: npm publish
workflows:
  test:
    jobs:
      - cancel_draft_build:
          filters:
            branches:
              ignore: /develop/
          context: cancel-draft
      - test_all:
          context:
            - slack-secret
            - alchemy-secret
      - npm-publish:
          requires:
            - test_all
          filters:
            branches:
              only: /develop/
          context:
            - npm-secret
